spring:
  application:
    name: statement-delivery-service

  mail:
    host: imap.gmail.com
    port: 993
    username: ${MAIL_USERNAME}
    password: ${MAIL_CODE}
    properties:
      mail:
        store:
          protocol: imaps
        imaps:
          timeout: 10000
          connectiontimeout: 10000